runtime: python27
api_version: 1
threadsafe: true

builtins:
  - deferred: on

handlers:
- url: /.*
  script: main.app
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin